### ISSUE TITLE
Exception when using dialog without theme

### ISSUE THREAD

**Issue by omihaz** [fengdai/AlertDialogPro#23]
If I not modify theme and not modify code, just replace AlertDialog to AlertDialogPro, my app crashes with this exception:
12-02 15:41:30.870    7189-7189/com.omihaz.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.omihaz.app, PID: 7189
    android.content.res.Resources$NotFoundException: Resource ID #0x0

This occurs because by default <item name="adpLayout">@null</item>
And 
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
            at com.alertdialogpro.internal.AlertController.installContent(AlertController.java:193)

Cannot inflate null resource.
You need provide some base theme as default.

**Comment by Vouskopes** [comment]
I am highly likely having same issue. Even when I have add all alertdialogpro dependencies to gradle and set alertDialogProTheme attribute app crashes on dialog.show:
```
10-14 20:18:01.911  13006-13006/cz.android.vouskopes D/AndroidRuntime﹕ Shutting down VM
10-14 20:18:01.913  13006-13006/cz.android.vouskopes E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: cz.android.vouskopes, PID: 13006
    android.content.res.Resources$NotFoundException: Resource ID #0x0
            at android.content.res.Resources.getValue(Resources.java:1233)
            at android.content.res.Resources.loadXmlResourceParser(Resources.java:2598)
            at android.content.res.Resources.getLayout(Resources.java:1049)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:412)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
            at com.alertdialogpro.internal.AlertController.installContent(AlertController.java:193)
            at com.alertdialogpro.AlertDialogPro.onCreate(AlertDialogPro.java:166)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
            at android.app.Dialog.show(Dialog.java:274)
            at cz.android.vouskopes.MainActivity.backupData(MainActivity.java:301)
            at cz.android.vouskopes.MainActivity.onOptionsItemSelected(MainActivity.java:190)
```

**Comment by fengdai** [comment]
What's your MainActivity's theme? Does it inherit the Application's theme or other theme which contains the ```alertDialogProTheme``` attribute?

**Comment by Vouskopes** [comment]
In my application theme:
```
    <item name="alertDialogProStyle">@style/YourAlertDialogProStyle</item>
    <item name="alertDialogProTheme">@style/AlertDialogPro.Holo.Light</item>
```
in YourAlertDialogProStyle:(even when I tried to disable this)
```
 <style name="YourAlertDialogProStyle" parent="Widget.AlertDialogPro.Holo.Light">
        <item name="adpTitleDividerBackground">@color/dialog_divider</item>
 </style>
```
My app theme is dependent on Theme.Holo.Light.DarkActionBar
Your library is dependent on AppCompat library thus It seems to me that application theme must be based on AppCompat's themes. Mustn't it?
thx I appreciate your work and time

**Comment by fengdai** [comment]
You should use ```Theme.AlertDialogPro.Holo.Light```:
```
<item name="alertDialogProTheme">@style/Theme.AlertDialogPro.Holo.Light</item>
```

**Comment by fengdai** [comment]
Just inherit ```Theme.AlertDialogPro.Holo.Light``` and override attribute ```adpTitleDividerBackground```, if you wanna change it:
```
<style name="YourAlertDialogProTheme" parent="Theme.AlertDialogPro.Holo.Light">
        <item name="adpTitleDividerBackground">@color/dialog_divider </item>
</style>
```
And don't forget to set it to your app's theme:
```
<item name="alertDialogProTheme">@style/YourAlertDialogProTheme</item>
```
