### ISSUE TITLE
ProgressDialogPro exception

### ISSUE THREAD

**Issue by marbat87** [fengdai/AlertDialogPro#44]
Hi,

I'm using this great library in my application.
I'm getting the following crash report on a Lenovo A916 with Android 4.4, when showing a indeterminate ProgressDialogPro:

<pre>
android.content.res.Resources$NotFoundException: Resource ID #0x0
at android.content.res.Resources.getValue(Resources.java:1133)
at android.content.res.Resources.loadXmlResourceParser(Resources.java:2381)
at android.content.res.Resources.getLayout(Resources.java:949)
at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:305)
at com.alertdialogpro.internal.AlertController.installContent(Unknown Source)
at com.alertdialogpro.AlertDialogPro.onCreate(Unknown Source)
at com.alertdialogpro.ProgressDialogPro.onCreate(Unknown Source)
at android.app.Dialog.dispatchOnCreate(Dialog.java:361)
at android.app.Dialog.show(Dialog.java:262)
at it.cammino.risuscito.PaginaRenderActivity.cmdPrepare(Unknown Source)
at it.cammino.risuscito.PaginaRenderActivity.access$900(Unknown Source)
at it.cammino.risuscito.PaginaRenderActivity$7.onClick(Unknown Source)
at android.view.View.performClick(View.java:4463)
at android.view.View$PerformClick.run(View.java:18772)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
at dalvik.system.NativeStart.main(Native Method)
</pre>

My code is just:
<pre>
mp3Dialog = new ProgressDialogPro(PaginaRenderActivity.this);
mp3Dialog.setMessage(getResources().getString(R.string.wait));
mp3Dialog.setOnDismissListener(new OnDismissListener() {
            @Override
            public void onDismiss(DialogInterface arg0) {
                setRequestedOrientation(prevOrientation);
            }
        });
mp3Dialog.show();
</pre>

I set correctly the theme in my settings:

<pre>
&lt;style name="Theme.MyTheme" parent="Theme.AppCompat.Light.NoActionBar">
     ..
        &lt;item name="alertDialogProTheme">@style/AppTheme.FlavoredMaterialLight&lt;/item>
&lt;/style>

&lt;style name="AppTheme.FlavoredMaterialLight" parent="Theme.AlertDialogPro.Material.Light">
        &lt;item name="colorAccent">@color/theme_accent&lt;/item>
 &lt;/style>
</pre>

It seems that the error occurs only on this particual device, as I tested my application on many Kitkat devices and this crash never occurred.

Any help?

Thanks in advance.
Marcello

**Comment by fengdai** [comment]
That's weird. The layout's resource ID of the ProgressDialogPro is #0x0. Be honest, I don't know the actual reason only if I can get that Lenovo A916 with Android 4.4.

**Comment by fengdai** [comment]
Which theme did your PaginaRenderActivity use?

**Comment by marbat87** [comment]
It uses the following theme on kitkat:

<pre>
&lt;style name="AppTheme" parent="Theme.MyTheme" >
        &lt;item name="toolbar_shadow">@drawable/toolbar_shadow&lt;/item>
&lt;/style> 
</pre>

The parent is the one which I mentioned above.

**Comment by fengdai** [comment]
Hi. I want to know wether ProgressDialogPro has obtained the right layout id. Please add below code to your PaginaRenderActivity's onCreate method. And log the value of ```layoutId```. Tell me the result. It should not be 0x0.

```java
        TypedValue outValue = new TypedValue();
        getTheme().resolveAttribute(com.alertdialogpro.R.attr.alertDialogProTheme,
                outValue,
                true);
        int layoutId = new ContextThemeWrapper(this, outValue.resourceId).getTheme().obtainStyledAttributes(null,
                com.alertdialogpro.R.styleable.AlertDialogPro,
                com.alertdialogpro.R.attr.alertDialogProStyle, 0).getResourceId(
                com.alertdialogpro.R.styleable.AlertDialogPro_adpProgressLayout, 0);
```

**Comment by marbat87** [comment]
It is not
<pre>03-25 12:50:18.672  11364-11364/it.cammino.risuscito I/class it.cammino.risuscito.PaginaRenderActivity﹕ layoutId: 2130968618 </pre>

**Comment by fengdai** [comment]
Ran with that Lenovo A916?

**Comment by marbat87** [comment]
Unfortunately not :( I don't own that phone. I got the error from an user through the play store.

**Comment by fengdai** [comment]
: (

**Comment by marbat87** [comment]
Any idea? I have no idea on how to replicate the issue...

**Comment by fengdai** [comment]
How many users have been affected by this issue? If the error occurs only on that Lenovo A916 now. I recommend you to hold it until you get more reports.

**Comment by marbat87** [comment]
That's the only one user, and the current version of the application has been in production for one month.

**Comment by marbat87** [comment]
I solved the problem using a normal AlertDialogPro and inflating, as custom view, the same layout took from the ProgressDialogPro.

**Comment by jelmertjuh** [comment]
Same exception on my OnePlus One (Android 5.0.2 stock).

alertdialogpro-theme-material:0.2.3 / minSdkVersion 21 / compileSdkVersion 22
