### ISSUE TITLE
Resource not found Exception for Api > 21

### ISSUE THREAD

**Issue by gustavaa** [fengdai/AlertDialogPro#51]
Hi!
I am experiencing an exception that only occurs on api 21 or higher:
```java
    06-04 10:22:07.076    3484-3484/test.testap E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: test.testapp, PID: 3484
    android.content.res.Resources$NotFoundException: Resource ID #0x0
            at android.content.res.Resources.getValue(Resources.java:1233)
            at android.content.res.Resources.loadXmlResourceParser(Resources.java:2598)
            at android.content.res.Resources.getLayout(Resources.java:1049)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:412)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:377)
            at com.alertdialogpro.internal.AlertController.installContent(AlertController.java:193)
            at com.alertdialogpro.AlertDialogPro.onCreate(AlertDialogPro.java:166)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
            at android.app.Dialog.show(Dialog.java:274)
            at com.alertdialogpro.AlertDialogPro$Builder.show(AlertDialogPro.java:774)
            at test.testapp.MyResultsActivity.onOptionsItemSelected(MyResultsActivity.java:164)
```

This is how I use AlertdialogPro:
```java
    AlertDialogPro.Builder builder = new AlertDialogPro.Builder(this);
                builder.setTitle("Choose race");
                builder.setCancelable(true);
                builder.setView(R.layout.choose_race_dialog);
                builder.show();
```
So to clarify on Api 19 this works wonderful, I get a clean Lollipop-style dialog. But it crashes on Lollipop.

I style it like:
```xml
  <style name="My.Theme" parent="Theme.AppCompat.Light">
      ....
        <item name="alertDialogProTheme">@style/MyAlertDialogProTheme</item>
      ....
  </style>

    <style name="MyAlertDialogProTheme" parent="Theme.AlertDialogPro.Material.Light">
        <item name="android:windowBackground">@drawable/dialog_background</item>
    </style>

```
I have also tried to not use any particular styling in my theme but that does not seem to make any difference.

I included the library in my project through Gradle like this:
```gradle
    dependencies {
        compile 'com.github.fengdai:alertdialogpro-theme-material:0.2.3'
    }
```

Any ideas to why I might get this exception?

**Comment by fengdai** [comment]
Hi. I can not reproduce this issue on my Nexus 5 (running lollipop). Can you send me a tiny project which can reproduce this issue?

**Comment by gustavaa** [comment]
Okay, sent a link to your email. Could reproduce the exact same problem for some reason though, but the exception is the same. Only now its occurring on both Api levels.

**Comment by fengdai** [comment]
Hi, About the crash of the project you sent to me, the actual reason is that you have forgotten to add ```alertDialogProTheme``` to your theme:

```
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="alertDialogProTheme">@style/MyAlertDialogProTheme</item>
    </style>
```
After I add it. Everything is Ok.

**Comment by gustavaa** [comment]
Oh sorry that was very forgetful of me, the project I sent you was put together real fast. However that is not the reason behind the crash in my real project, so I will se if I can reproduce the real problem and then I will get back to you.

**Comment by gustavaa** [comment]
Okay so now I feel stupid. It turns out that my project had a v21/themes that for some reason was not showing in Android Studios. I had to invalidate Cache for it to show up, and of course it was missing the "alertDialogProTheme" attribute. Sorry for wasting your time.
